baseurl = "https://andyrlu.com/"
languageCode = "en"
title = "Andy Lu's Blog"
theme = "kiss"
copyright = "&copy; Andy Lu 2020"
disqusShortname = ""
googleAnalytics = "UA-90403596-2"
Paginate = 50 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Andy Lu" # Author full name
authorEmail = "andy@andyrlu.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "_andy_lu_"
github = "luandy64"
#email = "andy@andyrlu.com"
linkedin = "andyrlu"
# facebook = ""
# instagram = ""
# codepen = ""
# rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
#platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]
platforms = ["twitter","github","linkedin"]

# [params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

#[params.fathomAnalytics]
#rootURL = "//fathom.example.com/"

[params.panelbear]
siteID = "1dDaNKWztfE"

[taxonomies]
tag ="tags"

#[blackfriday]
#hrefTargetBlank = true

[params.sections_left]
"/sundial" = "Sundial"
"/databooze" = "DataBooze"
